{% set name = "zeroc-ice" %}
{% set version = "3.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dc79a1eaad1d1cd1cf8cfe636e1bc413c60645e3e87a5a8e9b97ce882690e0e4
  patches:
    - patch

build:
  number: 0
  skip: true  # [win]
  entry_points:
    - slice2py=slice2py:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - bzip2
    - openssl
    - libiconv
  run:
    - python
    - bzip2
    - openssl
    - libiconv

test:
  imports:
    - Glacier2
    - Ice
    - Ice.Py3
    - IceBox
    - IceGrid
    - IceMX
    - IcePatch2
    - IceStorm
  commands:
    - slice2py --help

about:
  home: https://zeroc.com
  license: GNU General Public v2 (GPLv2)
  license_family: GPL2
  license_file:
    - ICE_LICENSE
  summary: Ice is a comprehensive RPC framework with support for Python, C++, .NET, Java, JavaScript and more.

extra:
  recipe-maintainers:
    - dpryan79
